blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/b14cknc0d3/open_workout/discussions/new?category=q-a
    about: Ask a question about using the Open Workout app or a general inquiry.
  - name: Report a security vulnerability
    url: https://github.com/b14cknc0d3/open_workout/security/policy
    about: Please report security vulnerabilities responsibly.
